### ISSUE TITLE
Replace DWI with CS-DSI

### ISSUE THREAD

**Issue by tsalo** [PennLINC/mobilephenomics#8]
Elements we'd like (@mattcieslak can you expand?):

1. Magnitude + phase reconstruction
2. Reverse phase-encoded b=0 scans with magnitude+phase reconstruction enabled as well.

**Comment by mattcieslak** [comment]
this is a GOOD IDEA

**Comment by mattcieslak** [comment]
we should use the HASC sequences from Hamsi's paper. If possible, an AP and PA version would be incredible, but we can fall back to just some reverse PE direction b=0s

**Comment by tsalo** [comment]
The CS-DSI OpenNeuro repo has HASC55 and HASC92. Is the difference just the number of directions? In which case I assume 92 is better than 55.

**Comment by mattcieslak** [comment]
I think it's only marginally better. What's neat is that there are 2 HASC-55 scans that sample unique coordinates in q-space, so we could do one of them in AP and another in PA, resulting in a total of HASC-110

**Comment by tsalo** [comment]
Ah, gotcha! So the priority list would be:

1. AP HASC 55 + PA HASC 55
2. AP HASC 92 + PA B=0
3. AP HASC 55 + PA B=0

**Comment by mattcieslak** [comment]
this sounds good, we may also be able to get a PA scan of just the low-b parts of the first HASC-55 that way we can use the drbuddi multimodal method. I bet we could get that into less than 3 minutes
